### ISSUE TITLE
Task 6: Perform a simple EDA in R

### ISSUE THREAD

**Issue by IfyAnene7** [UBC-MDS/525_group16#7]
6. Perform a simple EDA in R
rubric={correctness:15,reasoning:10}

- [x] Pick an approach to transfer the dataframe from python to R.

1. Parquet file
2. Feather file
3. Pandas exchange
4. Arrow exchange

- [x] Discuss why you chose this approach over others.

**Comment by chenzhao299** [comment]
Finished all tasks related to task 6
